# Generated by Django 5.1.1 on 2024-10-02 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("createdat", models.DateTimeField(default=django.utils.timezone.now)),
                ("updatedat", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "In Maintenance"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("maxparticipants", models.IntegerField(blank=True, null=True)),
                ("totalmessages", models.IntegerField(default=0)),
                ("private", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("privatekey", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "usertype",
                    models.CharField(
                        choices=[("registered", "Registered"), ("guest", "Guest")],
                        default="guest",
                        max_length=32,
                    ),
                ),
                (
                    "lastseen",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "datejoined",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("lastlogin", models.DateTimeField(blank=True, null=True)),
                ("isactive", models.BooleanField(default=False)),
                ("ipaddress", models.GenericIPAddressField(blank=True, null=True)),
                ("guesttoken", models.CharField(blank=True, max_length=512, null=True)),
                ("useragent", models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatroom",
            name="createdby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rooms",
                to="chat.user",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="onlineparticipants",
            field=models.ManyToManyField(
                blank=True, related_name="online_participants", to="chat.user"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="joined_rooms", to="chat.user"
            ),
        ),
    ]
